[versions]
javafx = "22.0.2"
kotlin = "2.1.21"
kotest = "5.9.1"
testfx = "4.0.18"
coroutines = "1.10.2"
jakta = "0.14.21"

[libraries]
google-guava = "com.google.guava:guava:33.4.8-jre"
javafx = { module = "org.openjfx:javafx", version.ref = "javafx" }
javafx-base = { module = "org.openjfx:javafx-base", version.ref = "javafx" }
javafx-graphics = { module = "org.openjfx:javafx-graphics", version.ref = "javafx" }
javafx-controls = { module = "org.openjfx:javafx-controls", version.ref = "javafx" }
javafx-fxml = { module = "org.openjfx:javafx-fxml", version.ref = "javafx" }
javafx-swing = { module = "org.openjfx:javafx-swing", version.ref = "javafx" }
jakta =  { module = "it.unibo.jakta:jakta-dsl", version.ref = "jakta" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotest-junit5-jvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-javafx = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-javafx", version.ref = "coroutines" }
kotest-assertions-core-jvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
mockk = "io.mockk:mockk:1.14.5"
testfx-core = { module = "org.testfx:testfx-core", version.ref = "testfx" }
testfx-junit = { module = "org.testfx:testfx-junit5", version.ref = "testfx" }
openjfx-monocle = "org.testfx:openjfx-monocle:17.0.10"

[bundles]
kotlin-testing = [
    "kotest-junit5-jvm",
    "kotest-assertions-core-jvm",
    "mockk",
]
javafx-modules = [
    "javafx-base",
    "javafx-graphics",
    "javafx-controls",
    "javafx-fxml",
    "javafx-swing",
]
testfx = [ "testfx-core", "testfx-junit", "openjfx-monocle" ]
coroutines = ["kotlin-coroutines", "kotlin-coroutines-javafx"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-qa = "org.danilopianini.gradle-kotlin-qa:0.75.0"
kotlin-dokka = { id = "org.jetbrains.dokka", version = "2.0.0" }
git-semantic-versioning = "org.danilopianini.git-sensitive-semantic-versioning:6.0.1"
shadowJar = "com.github.johnrengelman.shadow:8.1.1"
